# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    admin_email: 'julienbasquin@hotmail.fr'

services:
    # le name du tag "kernel.event_listener" est propre au framework. Tagger ce service permet de le déclarer en tant qu'écouteur
    # event est le nom de l'événement qui sera envoyé par le répartiteur.
    # method permet de spécifier quelle méthode de la classe sera exécutée.
    App\EventListener\ExceptionListener:
        tags:
            - {name: kernel.event_listener, event: foo, method: doSomething, priority: 999}
    # default configuration for services in *this* file
    _defaults:
        bind:
            # Suffisant pour que le MailLogger soit bien instancié.
            $adminEmail: '%admin_email%'
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Disponible seulement pour ce service
    App\Services\MailLogger:
        arguments:
            $adminEmail: 'julienbasquin@hotmail.fr'
